[theme]
base = "light"

# Primary color for buttons, highlights, and active elements
primaryColor = "#338AFF"              # Blue buttons and accents

# Backgrounds
backgroundColor = "#FDFBF7"           # Main background (cream)
secondaryBackgroundColor = "#338AFF"  # Sidebar / navigation (blue)

# Text color (auto-applies where background is light)
textColor = "#364153"                 # Text for cream backgrounds

# Font
font = "Inter"

#youtube
API_BASE_URL = "https://api.rx.theramuse.net/api/youtube/search"
[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = true
address = "0.0.0.0"
